# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.API/*.csproj'
    arguments: '--configuration Release'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: HIS-SPA

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: run build
    workingDir: HIS-SPA

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'angular'
    targetPath: 'HIS-SPA/dist'